[formatting]
reorder_keys = false
reorder_array = false


[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true
reorder_array = true
