[package]
name = "tilc_resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal crates
tilc_ast = { workspace = true }
tilc_hir = { workspace = true }
tilc_middle = { workspace = true }
tilc_span = { workspace = true }
