[package]
name = "tilc_session"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal crates
tilc_ast = { workspace = true }
tilc_span = { workspace = true }

# External packages
indexmap = { workspace = true }
parking_lot = { workspace = true }
