[package]
name = "tilc_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
# External packages
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
