[package]
name = "tilc_query_system"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal crates
tilc_span = { workspace = true }

# External packages
indexmap = { workspace = true }
parking_lot = { workspace = true }
