use tilc_macros::symbols;


// NOTE: Do not remove this import (It is used for importing Symbol for macro generated code)
use super::Symbol;
symbols! {
  Keywords {
    // Abstract : "",
    // As: "",
    // Async: "",
    // Auto: "",
    // Await: "",
    // Become: "",
    // Builtin: "",
    // Box: "",
    // Break: "",
    // Catch: "",
    Const: "turaqty",
    // Continue: "jalgastyr",
    // Crate: "", How to name crate?
    // Default: "",
    // Do : "",
    // Dyn: "",
    Else: "bolmasa",
    // Enum: "",
    // Extern: "",
    False: "burys",
    // Final: "",
    Function: "fx",
    For: "eger",
    // Gen: "",
    // If: "",
    // Impl: "",
    // In: "",
    Let: "ainymaly",
    // Loop: "",
    // Macro: "macro",
    // MacroRules: "",
    // Match: "",
    // Mod: "",
    // Move: "",
    Mut : "auspaly",
    // Override: "",
    // Priv: "",
    // Pub: "",
    // Raw: "",
    // Ref: "",
    Return: "qaitar",
    // Reuse: "",
    // Safe: "qauipsiz",
    // SelfValue : "ozi",
    // SelfType : "Ozi",
    // Static: "",
    // StaticLifetime: "",
    Struct: "zat",
    // Super: "",
    Trait: "qasiet",
    True: "durys",
    // Try: "",
    // Type: "",
    // Typeof: "",
    // UnderscoreLifetime: "",
    // Union: "",
    // Unsafe: "Qauipti",
    // Unsized: "sheksiz",
    // Use: "qoldan",
    // Virtual: "",
    // Where: "",
    // While: "",
    // Yeet: "laqtyr",
    // Yield: "jiber",
  }
}


// NOTE: kw generated in symbols macro
pub use kw::*;
